### ISSUE TITLE
Where is the model_VGG2D file?

### ISSUE THREAD

**Issue by illwy** [sgluege/Robust-Drone-Detection-and-Classification#1]
Thank you for your reply.

**Comment by sgluege** [comment]
See last section of the README.md

Trained models:

You can download the models and evaluation results from the experiment above from [Zenodo](https://zenodo.org/records/14065652).

**Comment by sgluege** [comment]
Hey,

I thought you were referring to the trained model(s)...
Actually I had the lib/ directory in .gitignore, and thus didn't upload the code for the model. 
Sorry my bad.

Thanks for pointing this out :)

**Comment by illwy** [comment]
So could you provide the model_VGG2D file? Thank you very much.

**Comment by illwy** [comment]
I've already seen it. Thank you.
