### ISSUE TITLE
Essay Questions

### ISSUE THREAD

**Issue by ycycyczzu** [sgluege/Robust-Drone-Detection-and-Classification#2]
Noise vectors (Bluetooth, Wi-Fi, Amplifier, Gauss) n with samples i∈{1,…k} were normalized to a mean power of 1 with--Original paper
Excuse me, what is an amplifier? I noticed that it was not mentioned in the noise above.

**Comment by sgluege** [comment]
We have only a single Noise class. It is constructed from samples of Gaussian Noise (mixed with itself) and Wi-Fi/Bluetooth/Amplifier Noise mixed with Gaussian Noise.

I guess the effect of the amplifier noise is negligible for the model during training but makes a difference when deployed to an actual detection system that gets the signal directly from an antenna -> amplifier -> SDR setup. Adding some noise from the amplifier prevents the model to make unreasonable predictions if, for instance, no antenna is attached to the detection system.
